// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: internal/transport/pb/job.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_QUEUED      JobStatus = 1
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 2
	JobStatus_JOB_STATUS_SUCCEEDED   JobStatus = 3
	JobStatus_JOB_STATUS_FAILED      JobStatus = 4
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_QUEUED",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_SUCCEEDED",
		4: "JOB_STATUS_FAILED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_QUEUED":      1,
		"JOB_STATUS_RUNNING":     2,
		"JOB_STATUS_SUCCEEDED":   3,
		"JOB_STATUS_FAILED":      4,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_transport_pb_job_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_internal_transport_pb_job_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_transport_pb_job_proto_rawDescGZIP(), []int{0}
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=pb.JobStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_internal_transport_pb_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_pb_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_internal_transport_pb_job_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Job) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_internal_transport_pb_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_pb_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_pb_job_proto_rawDescGZIP(), []int{1}
}

func (x *GetJobRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_internal_transport_pb_job_proto protoreflect.FileDescriptor

const file_internal_transport_pb_job_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/transport/pb/job.proto\x12\x02pb\"<\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x06status\x18\x02 \x01(\x0e2\r.pb.JobStatusR\x06status\"\x1f\n" +
	"\rGetJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id*\x87\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATUS_QUEUED\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_SUCCEEDED\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x0425\n" +
	"\vJobsService\x12&\n" +
	"\x06GetJob\x12\x11.pb.GetJobRequest\x1a\a.pb.Job\"\x00B$Z\"pet-study/internal/transport/pb;pbb\x06proto3"

var (
	file_internal_transport_pb_job_proto_rawDescOnce sync.Once
	file_internal_transport_pb_job_proto_rawDescData []byte
)

func file_internal_transport_pb_job_proto_rawDescGZIP() []byte {
	file_internal_transport_pb_job_proto_rawDescOnce.Do(func() {
		file_internal_transport_pb_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_pb_job_proto_rawDesc), len(file_internal_transport_pb_job_proto_rawDesc)))
	})
	return file_internal_transport_pb_job_proto_rawDescData
}

var file_internal_transport_pb_job_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_transport_pb_job_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_transport_pb_job_proto_goTypes = []any{
	(JobStatus)(0),        // 0: pb.JobStatus
	(*Job)(nil),           // 1: pb.Job
	(*GetJobRequest)(nil), // 2: pb.GetJobRequest
}
var file_internal_transport_pb_job_proto_depIdxs = []int32{
	0, // 0: pb.Job.status:type_name -> pb.JobStatus
	2, // 1: pb.JobsService.GetJob:input_type -> pb.GetJobRequest
	1, // 2: pb.JobsService.GetJob:output_type -> pb.Job
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_transport_pb_job_proto_init() }
func file_internal_transport_pb_job_proto_init() {
	if File_internal_transport_pb_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_pb_job_proto_rawDesc), len(file_internal_transport_pb_job_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_transport_pb_job_proto_goTypes,
		DependencyIndexes: file_internal_transport_pb_job_proto_depIdxs,
		EnumInfos:         file_internal_transport_pb_job_proto_enumTypes,
		MessageInfos:      file_internal_transport_pb_job_proto_msgTypes,
	}.Build()
	File_internal_transport_pb_job_proto = out.File
	file_internal_transport_pb_job_proto_goTypes = nil
	file_internal_transport_pb_job_proto_depIdxs = nil
}
